# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-st-stm32mp-append"
BBFILE_PATTERN_meta-st-stm32mp-append = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-st-stm32mp-append = "6"

LAYERDEPENDS_meta-st-stm32mp-append = "core"
LAYERSERIES_COMPAT_meta-st-stm32mp-append = "scarthgap"
